### ISSUE TITLE
Missing Dockerfiles

### ISSUE THREAD

**Issue by jacobdanovitch** [RTIInternational/gobbli#9]
## System Information
- OS platform and distribution: Ubuntu 18.04
- gobbli version: 0.0.2
- Python version: 3.7
- Other information relevant to the problem (GPU model, Docker version, etc): Running on a GCP VM, fwiw

## Description

It seems as though the Dockerfiles for the models (i.e., `site-packages/gobbli/models/use`) are missing when installed from pip. Not sure if I've done something wrong. I assume this can simply be fixed by building from source and running `pip install -e .` - will try to check later.

## Code for Minimal Reproducible Example

```shell
pip install gobbli
```

## Output

```python
APIError: 500 Server Error: Internal Server Error ("Cannot locate specified Dockerfile: Dockerfile")
``` 

My current fix was to just `wget` all the missing files and such but I will try to install from source rather than pip. 

P.S. Awesome work on this library, the results have been great so far.

**Comment by jasonnance** [comment]
Interesting...  No, you're right -- I don't see the Dockerfiles when downloading the source from PyPI.  I guess I need to configure something somewhere to make sure they get uploaded?  I'll look into it.

**Comment by jasonnance** [comment]
Added Dockerfiles to `MANIFEST.in` and verified they're showing up on PyPI now under the new release (0.0.3).  Apologies for the rather egregious oversight... Thanks for the report!

**Comment by jacobdanovitch** [comment]
> Added Dockerfiles to `MANIFEST.in` and verified they're showing up on PyPI now under the new release (0.0.3). Apologies for the rather egregious oversight... Thanks for the report!

No worries! Thanks for the quick fix, I'll give it a go again a bit later.

**Comment by jacobdanovitch** [comment]
Was trying out the augment modules and the `BERTMaskedLM` module is experiencing the same problem - looking at the `site-packages/gobbli` again, it seems that the Dockerfile isn't included for it. 

It is there for the models, though.

**Comment by jasonnance** [comment]
Ugh, you're right -- I reproduced that and found a few other issues with the wheel and source distribution.  Hopefully I've got it all this time.  Uploaded a new release (0.0.5) and verified I can build a model from `gobbli.model` and `gobbli.augment` from the version installed by `pip install gobbli` via both wheel and source.  Thanks for your patience and please report back if you have any other issues!
